import Head from "next/head"
import DefaultLayout from "../layout/DefaultLayout"
import Dashboard from '../components/Dashboard'

export default function Home() {
  return (
    <>
      <Head>
        <title>My Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Dashboard />
      </DefaultLayout>
    </>
  )
}
